import Image from 'next/image';
import { ArrowUpRight } from 'lucide-react';

const services = [
    { title: 'Next.js & React', description: 'High-performance static site architecture.' },
    { title: 'Powered by Gemini', description: "Content and code logic generated by Google's Gemini models." },
    { title: 'Gemini Imagery', description: 'Visual aesthetics synthesized by multimodal AI.' },
    { title: 'n8n Automation', description: 'Content pipelines powered by automated workflows.' },
];

export default function SplitSection() {
    return (
        <section className="mb-24">
            <div className="container mx-auto px-4">
                <div className="text-center mb-16">
                    <h2 className="text-3xl font-bold tracking-tight">The Tech Stack</h2>
                </div>
                <div className="grid md:grid-cols-2 gap-12 items-center">
                    <div className="relative aspect-[4/3] bg-gray-100">
                        <Image
                            src="/images/architecture.png"
                            alt="Architectural detail"
                            fill
                            className="object-cover grayscale"
                        />
                    </div>
                    <div className="space-y-8">
                        <ul className="space-y-0">
                            {services.map((service) => (
                                <li key={service.title} className="border-b border-gray-200 py-6 flex justify-between items-center group cursor-pointer hover:bg-gray-50 px-4 transition-colors">
                                    <div className="text-left">
                                        <div className="font-bold mb-1">{service.title}</div>
                                        <div className="text-sm text-gray-500">{service.description}</div>
                                    </div>
                                    <ArrowUpRight className="w-5 h-5 text-gray-400 group-hover:text-black transition-colors" />
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    );
}
